import Head from "next/head";
import Image from "next/image";

// just a test remove later
import ObfuscatedText from "@/components/ObfuscatedText/ObfuscatedText";

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <ObfuscatedText>
               The craft of William Laurel Alvarez, a creative software developer with a
               passion for design.
            </ObfuscatedText>
         </main>
      </>
   );
}

async function getStaticProps() {}
